TWITTER_KEY= "{TWITTER_KEY_HERE}" \
TWITTER_SECRET="{TWITTER_SECRET_HERE}" \
TWITTER_TOKEN="{TWITTER_ACCESS_TOKEN_HERE}" \
TWITTER_TOKEN_SECRET="{TWITTER_ACCESS_TOKEN_SECRET_HERE}" \
WATSON_NLC_CREDENTIAL="{WATSON_NLC_USER_HERE}:{WATSON_NLC_PASSWORD_HERE}" \
WATSON_NLC_CLASSIFIER="{WATSON_NLC_CLASSIFIER_ID_HERE}" \
node ./app.js

